Assignment link:                                                                              
https://drive.google.com/file/d/1TZnso_qxuqgMjGyhcpGshzt5S0sg1qve/view

**Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.**

**HINT:** 
Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

Numpy link:                                                                 
https://numpy.org/doc/stable/reference/generated/numpy.vander.html

In [1]:
def myvander(x,N,increasing=False):
    R= []
    if increasing == False:
        for i in range(N):
            a = list(x**(N-i-1))
            R.append(a)
        return np.array(R).T
            
    else:
        for i in range(N):
            a = list(x**i)
            R.append(a)
        return np.array(R).T       

In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
N = 4

In [3]:
print(myvander(x,N,False))
print()
print(myvander(x,N,True))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


In [4]:
import numpy as np
print(np.vander(x,N,False))
print()
print(np.vander(x,N,True))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


---

**(2) Write a function to find moving average in an array over a window:                               
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3**

In [5]:
from functools import*
def mov_avg(l,k):
    m = len(l)-k+1                                       # m = 7
    for i in range(m):                                   # 0,1,2,3,4,5,6 -->7times
        r = reduce(lambda x,y: x+y,l[i:i+k])/ k          # l[0:4]/4,l[1:4+1]/4,l[2:4+2]/4,...
        print("y{} = {}".format(i+1,round(r,2)))



# r = l[i:i+k].sum() / k --> if l is numpy array

In [6]:
l =  [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
mov_avg(l,k)

y1 = 5.0
y2 = 4.67
y3 = 5.67
y4 = 6.67
y5 = 9.67
y6 = 28.67
y7 = 49.33
y8 = 72.67
y9 = 84.0
y10 = 93.33
y11 = 116.33
